# Generated by Django 5.1 on 2026-09-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madflixapp', '0002_movielog'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielog',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
    ]
