# Generated by Django 5.1 on 2026-09-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madflixapp', '0003_movielog_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='watched_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
