# Generated by Django 5.1 on 2026-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madflixapp', '0003_add_bannedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
