# Generated by Django 5.1 on 2026-09-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madflixapp', '0004_alter_movielog_watched_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
