# Generated by Django 5.1 on 2026-09-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madflixapp', '0010_reviewreplylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='media_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
